@url_base = http://localhost:5211/api/venda

### Efetuar uma venda a partir de um carrinho existente
### Certifique-se de que o carrinho com ID correspondente exista e contenha itens.
POST {{url_base}}/efetuar/8
Content-Type: application/json

{}

### Listar todas as vendas
GET {{url_base}}/listar

### Buscar venda por ID
GET {{url_base}}/buscar/1

### Listar contas a receber
GET {{url_base}}/contasareceber